<?php
	include("connect.php");
	unset($_SESSION[SESS_PRE.'_SESS_USER_ID']);
	unset($_SESSION[SESS_PRE.'_SESS_USER_NAME']);
	unset($_SESSION[SESS_PRE.'_SESS_USER_EMAIL']);
	unset($_SESSION[SESS_PRE.'_SESS_CORPORATE_CART_ID']);
	unset($_SESSION[SESS_PRE.'_SESS_GUEST_ID']);
	unset($_SESSION[SESS_PRE.'_SESS_CART_ID']);
	unset($_SESSION['MSG']);
	unset($$_SESSION['token']);
	$db->location(SITEURL.'login/');
	exit;
?>